apiVersion: v2
name: vitalam-ipfs
appVersion: '1.2.3'
description: A Helm chart for vitalam-ipfs
version: '1.2.3'
type: application
dependencies:
  - name: vitalam-node
    version: '0.23.5'
    repository: https://digicatapult.github.io/vitalam-node/
    condition: vitalamNode.enabled
    alias: vitalamNode
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
