image:
  repository: 'vitalam-ipfs'
  tag: 'latest'
  PullPolicy: Never

vitalamNode:
  enabled: true
  node:
    chain: dev
    flags:
    - "--rpc-external"
    - "--alice"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
